export const movieQuotes = [
  "Here's looking at you, kid.",
  "I'm going to make him an offer he can't refuse.",
  "You can't handle the truth!",
  "Go ahead, make my day.",
  "May the force be with you.",
  "You had me at 'hello.'",
  "I'll be back.",
  "We'll always have Paris.",
  "The first rule of Fight Club is: You do not talk about Fight Club.",
  "The truth is out there.",
  "I am the one who knocks.",
  "I am not a robot.",
  "I drink your milkshake!",
  "My precious.",
  "It's alive! It's alive!",
  "The horror... the horror...",
  "Here's Johnny!",
  "I am Iron Man.",
  "I see dead people.",
  "I am your father.",
  "It's not a tumor!",
  "I'm the king of the world!",
  "They may take our lives, but they'll never take our freedom!",
  "I'm gonna make him an offer he can't refuse.",
  "I'm the ghost with the most, babe.",
  "Say hello to my little friend!",
  "A boy's best friend is his mother.",
  "I'm not bad, I'm just drawn that way.",
  "It's not the years, honey. It's the mileage.",
  "I feel the need - the need for speed!",
  "Carpe diem. Seize the day, boys. Make your lives extraordinary.",
  "What we've got here is failure to communicate.",
  "I'm gonna get medieval on your ass.",
];

export const jokes = [
  "Why was the math book sad? It had too many problems.",
  "Why couldn't the bicycle stand up by itself? Because it was two-tired.",
  "Why was the computer cold? It left its Windows open.",
  "Why was the cat sitting on the computer? It wanted to keep an eye on the mouse.",
  "Why was the computer sick? It had a virus.",
  "Why was the computer cold? It left its Windows open.",
  "Why was the computer good at math? It had a lot of processors.",
  "Why did the computer get cold? It left its Windows open.",
  "Why did the computer go to the doctor? It had a virus.",
  "Why did the tomato turn red? Because it saw the salad dressing!",
  "Why did the chicken go to outer space? To see the mooon!",
  "Why couldn't the leopard play hide and seek? Because he was always spotted.",
  "Why was the math book unhappy? It had too many problems.",
  "Why was the broom late? It overswept.",
  "Why was the computer cold? It left its Windows open.",
  "Why was the computer cold? It left its Windows open.",
];

export const techPhrases = [
  "The code is more like guidelines anyway.",
  "I'm not arguing, I'm just explaining why I'm right.",
  "I'm not procrastinating, I'm just prioritizing other tasks.",
  "It's not a bug, it's an undocumented feature.",
  "I'm not ignoring you, I'm just in deep thought about this code.",
  "It's not a crash, it's a controlled shutdown.",
  "It's not a hack, it's an unauthorized use of resources.",
  "It's not a glitch, it's a temporary deviation from expected behavior.",
  "I'm not lost, I'm just taking the scenic route through the code.",
  "I'm not stuck, I'm just debugging.",
  "It's not a mistake, it's a learning opportunity.",
  "I'm not a tech support person, I'm a code wizard.",
  "I'm not a nerd, I'm a technologically advanced individual.",
  "I'm not a procrastinator, I'm a project optimizer.",
  "I'm not ignoring you, I'm just coding in the zone.",
  "I'm not a perfectionist, I just have high quality standards for my code.",
];

export const hipsterPhrases = [
  "I'm not like the other tourists, I'm a traveler.",
  "I only listen to vinyl records.",
  "I only drink craft beer.",
  "I only shop at thrift stores.",
  "I only eat at hole-in-the-wall restaurants.",
  "I'm not into mainstream stuff.",
  "I only use a film camera.",
  "I only go to independent coffee shops.",
  "I only wear vintage clothes.",
  "I'm not into corporate chains.",
  "I only go to small, local music festivals.",
  "I only read small, independent magazines.",
  "I'm not into mass-produced items.",
  "I only support local businesses.",
  "I'm not a follower, I'm a trendsetter.",
];
